### tested with ansible 2.10.2 and ubuntu 20.04 image
---

- hosts: all
  remote_user: ubuntu
  become: yes
  gather_facts: false

  tasks:
  - name: get hostname
    command: /bin/hostname
    register: vhostname

  - name: fix /etc/hosts
    lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.0\.1'
      line: "127.0.0.1 localhost {{ vhostname.stdout }}"
      owner: root
      group: root
      mode: 0644

  - name : enable password auth
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: "PasswordAuthentication yes"
      owner: root
      group: root
      mode: 0644

  - name: install HWE kernel
    apt: name=linux-generic-hwe-20.04 state=latest

  - name: install numad
    apt: name={{ item }} state=latest
    with_items:
      - numad
      - numactl

  - name: start numad service
    service: name=numad state=started enabled=yes

  - name: load users and passwords
    include_vars: users.yml
    tags: users
    
  # check dictionary is loading correctly
  #- name: show dictionary
  #  debug:
  #    var: user_passwords  

  - name: create users
    user: name="{{ item.key }}" password="{{ item.value }}" shell="/bin/bash" update_password=on_create
    with_dict: "{{ user_passwords }}"
    register: user_results
    tags: users

  - name: install conda and conda packages
    include_tasks: conda.yml
    become_user: "{{ item.item.key }}"
    with_items:
      - "{{ user_results.results }}"

  - name: update apt cache
    apt: update_cache=yes

  - name: install packages
    apt: name={{ item }} state=present
    with_items:
    - curl
    - build-essential
    - python-pip
    - python3-pip
    - git
    - python-setuptools
    - python-dev
    - cython
    - default-jre
    - gnuplot-x11
    - bioperl
    - libssl-dev
    - cmake
    - hdf5-tools
    - libdatetime-perl
    - libxml-simple-perl
    - libdigest-md5-perl
    - libfreetype6-dev
    - pkg-config
